// playerCXRank.js
// CX Rank
// Generated by SterbyToolsGo v2.13.0 on 2026-09-17
const playerCXRank = {
    current: {
    "100876140": {
        "cxRankScore": 400
    },
    "102263647": {
        "cxRankScore": 0
    },
    "103516442": {
        "cxRankScore": 0
    },
    "106162623": {
        "cxRankScore": 0
    },
    "10754439": {
        "cxRankScore": 0
    },
    "108546985": {
        "cxRankScore": 0
    },
    "112772047": {
        "cxRankScore": 0
    },
    "113690788": {
        "cxRankScore": 0
    },
    "11463573": {
        "cxRankScore": 0
    },
    "115742768": {
        "cxRankScore": 0
    },
    "18115624": {
        "cxRankScore": 0
    },
    "18297536": {
        "cxRankScore": 0
    },
    "26277677": {
        "cxRankScore": 0
    },
    "29321884": {
        "cxRankScore": 0
    },
    "29904762": {
        "cxRankScore": 0
    },
    "30658936": {
        "cxRankScore": 0
    },
    "32556489": {
        "cxRankScore": 0
    },
    "35869301": {
        "cxRankScore": 0
    },
    "36484758": {
        "cxRankScore": 0
    },
    "41742773": {
        "cxRankScore": 400
    },
    "51071110": {
        "cxRankScore": 0
    },
    "59566866": {
        "cxRankScore": 0
    },
    "60687252": {
        "cxRankScore": 0
    },
    "64676255": {
        "cxRankScore": 0
    },
    "66607264": {
        "cxRankScore": 400
    },
    "69676999": {
        "cxRankScore": 0
    },
    "70603922": {
        "cxRankScore": 0
    },
    "71028860": {
        "cxRankScore": 0
    },
    "72894129": {
        "cxRankScore": 0
    },
    "75174428": {
        "cxRankScore": 0
    },
    "79510960": {
        "cxRankScore": 0
    },
    "80018314": {
        "cxRankScore": 0
    },
    "80972473": {
        "cxRankScore": 0
    },
    "83339881": {
        "cxRankScore": 800
    },
    "83861839": {
        "cxRankScore": 0
    },
    "87244358": {
        "cxRankScore": 0
    },
    "87954282": {
        "cxRankScore": 0
    },
    "88203044": {
        "cxRankScore": 0
    },
    "89511116": {
        "cxRankScore": 0
    }
},
    previous: {}
};
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { playerCXRank };
}
