// playerCXBoss.js
// CX Boss
// Generated by SterbyToolsGo v2.4.4 on 2026-09-10
const playerCXBoss = {
    current: {
    "100876140": {
        "cxBossScore": 0
    },
    "102263647": {
        "cxBossScore": 0
    },
    "103516442": {
        "cxBossScore": 0
    },
    "106162623": {
        "cxBossScore": 0
    },
    "10754439": {
        "cxBossScore": 0
    },
    "108546985": {
        "cxBossScore": 0
    },
    "112772047": {
        "cxBossScore": 0
    },
    "113690788": {
        "cxBossScore": 0
    },
    "11463573": {
        "cxBossScore": 0
    },
    "115742768": {
        "cxBossScore": 0
    },
    "18115624": {
        "cxBossScore": 0
    },
    "18297536": {
        "cxBossScore": 0
    },
    "19575414": {
        "cxBossScore": 0
    },
    "26277677": {
        "cxBossScore": 0
    },
    "29321884": {
        "cxBossScore": 0
    },
    "29904762": {
        "cxBossScore": 0
    },
    "30658936": {
        "cxBossScore": 0
    },
    "32556489": {
        "cxBossScore": 0
    },
    "35869301": {
        "cxBossScore": 0
    },
    "36484758": {
        "cxBossScore": 0
    },
    "41742773": {
        "cxBossScore": 0
    },
    "51071110": {
        "cxBossScore": 0
    },
    "59566866": {
        "cxBossScore": 0
    },
    "60687252": {
        "cxBossScore": 0
    },
    "64676255": {
        "cxBossScore": 0
    },
    "66607264": {
        "cxBossScore": 0
    },
    "69676999": {
        "cxBossScore": 0
    },
    "70603922": {
        "cxBossScore": 0
    },
    "71028860": {
        "cxBossScore": 0
    },
    "72894129": {
        "cxBossScore": 0
    },
    "75174428": {
        "cxBossScore": 0
    },
    "79510960": {
        "cxBossScore": 0
    },
    "80018314": {
        "cxBossScore": 0
    },
    "80972473": {
        "cxBossScore": 0
    },
    "83339881": {
        "cxBossScore": 0
    },
    "83861839": {
        "cxBossScore": 0
    },
    "87244358": {
        "cxBossScore": 0
    },
    "87954282": {
        "cxBossScore": 0
    },
    "88203044": {
        "cxBossScore": 0
    },
    "89511116": {
        "cxBossScore": 0
    }
},
    previous: {}
};
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { playerCXBoss };
}
