// playerCXBoss.js
// CX Boss
// Generated by SterbyToolsGo v2.8.2 on 2026-09-13
const playerCXBoss = {
    current: {
    "100876140": {
        "cxBossScore": 767
    },
    "102263647": {
        "cxBossScore": 830
    },
    "103516442": {
        "cxBossScore": 846
    },
    "106162623": {
        "cxBossScore": 746
    },
    "10754439": {
        "cxBossScore": 748
    },
    "108546985": {
        "cxBossScore": 796
    },
    "112772047": {
        "cxBossScore": 734
    },
    "113690788": {
        "cxBossScore": 714
    },
    "11463573": {
        "cxBossScore": 768
    },
    "115742768": {
        "cxBossScore": 0
    },
    "18115624": {
        "cxBossScore": 804
    },
    "18297536": {
        "cxBossScore": 0
    },
    "19575414": {
        "cxBossScore": 0
    },
    "26277677": {
        "cxBossScore": 766
    },
    "29321884": {
        "cxBossScore": 818
    },
    "29904762": {
        "cxBossScore": 723
    },
    "30658936": {
        "cxBossScore": 739
    },
    "32556489": {
        "cxBossScore": 725
    },
    "35869301": {
        "cxBossScore": 785
    },
    "36484758": {
        "cxBossScore": 664
    },
    "41742773": {
        "cxBossScore": 0
    },
    "51071110": {
        "cxBossScore": 757
    },
    "59566866": {
        "cxBossScore": 761
    },
    "60687252": {
        "cxBossScore": 883
    },
    "64676255": {
        "cxBossScore": 767
    },
    "66607264": {
        "cxBossScore": 728
    },
    "69676999": {
        "cxBossScore": 736
    },
    "70603922": {
        "cxBossScore": 756
    },
    "71028860": {
        "cxBossScore": 0
    },
    "72894129": {
        "cxBossScore": 811
    },
    "75174428": {
        "cxBossScore": 772
    },
    "79510960": {
        "cxBossScore": 0
    },
    "80018314": {
        "cxBossScore": 727
    },
    "80972473": {
        "cxBossScore": 796
    },
    "83339881": {
        "cxBossScore": 859
    },
    "83861839": {
        "cxBossScore": 768
    },
    "87244358": {
        "cxBossScore": 831
    },
    "87954282": {
        "cxBossScore": 786
    },
    "88203044": {
        "cxBossScore": 757
    },
    "89511116": {
        "cxBossScore": 0
    }
},
    previous: {}
};
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { playerCXBoss };
}
